### ISSUE TITLE
[FEATURE]: Ability to force move devices between storage groups if SRDF Protected

### ISSUE THREAD

**Issue by rawstorage** [dell/ansible-powermax#19]
**Describe the solution you'd like**
When moving devices that are SRDF protected the Ansible, moving of devices is blocked.  API will allow me to do this. Customer HSBC have reverted to URI module to accomplish this

**Describe alternatives you've considered**
URI Module

**Additional context**
Customer needs to be able to force move devices in and out of SRDF storage groups keeping SRDF protection on the devices even if it will render them unmanageable, they maintain separate SG for SRDF and Provisioning so this is a common occurrence for them and a blocker for ansible

**Comment by anupamaloke** [comment]
This is fixed by #25
