### ISSUE TITLE
[FEATURE]: dellemc.powermax.storagegroup - Make vol_name an optional argument

### ISSUE THREAD

**Issue by jonathanhellman8** [dell/ansible-powermax#23]
Currently when using the storagegroup module to create new volumes to an existing storage group, vol_name needs to be provided to label the volume. Is there any way of not making vol_name a required input? There's no requirement in the storage array to label a volume when creating volumes for a SG. Currently I add a randomly generated string to vol_name to be able to use this module to create volumes to a SG over and over again without any vol_names conflicting. 

Or is there any other way of achieving the very same thing without having to add a random string to vol_name?

- name: Create new volumes for existing SG
  dellemc.powermax.storagegroup:
    unispherehost: "{{unispherehost}}"
    universion: "{{universion}}"
    verifycert: "{{verifycert}}"
    user: "{{user}}"
    password: "{{password}}"
    serial_no: "{{serial_no}}"
    sg_name: "foo"
    state: "present"
    volumes:
    - vol_name: "bar"
      size: 1
      cap_unit: "GB"
    vol_state: "present-in-group"

When not using a unique vol_name it does return:

"msg": "A volume with identifier bar but different size 6.0 GB already exists. Use a different identifier for volume creation. Currently, we support only unique identifiers for volume creation on PowerMax from Ansible"

**Comment by csalitros** [comment]
I could use this as well...  I usually just tag the volume with the SG Name is going into.

**Comment by anupamaloke** [comment]
@csalitros, this feature is going to be part of  v2.1.0 that is going to come out later this week.

**Comment by rawstorage** [comment]
if you omit the vol_name you can add multiple volumes in one change without the volume id, this is not an idempotent task though if you need your task to be idempotent then you should always use the volume name or add volume id for existing volumes to ensure idempotency.

**Comment by anupamaloke** [comment]
Closing the issue as it has been fixed by #28
