### ISSUE TITLE
[BUG]: meta/runtime.yml contains redirects that will stop working with ansible-core 2.14

### ISSUE THREAD

**Issue by felixfontein** [dell/ansible-powermax#24]
**Describe the bug**
The `redirect` entries in `meta/runtime.yml` do not contain FQCNs, but short names: https://github.com/dell/ansible-powermax/blob/1.8.0/meta/runtime.yml#L6-L81

This will result in an error with ansible-core 2.14, see https://github.com/ansible/ansible/pull/78755.

**Comment by Jennifer-John** [comment]
Closing this issue as it is fix as part of PR #28
