### ISSUE TITLE
[BUG]: Host WWNs not idempotent if input in different case

### ISSUE THREAD

**Issue by rawstorage** [dell/ansible-powermax#26]
**Describe the bug**

**To Reproduce**
- name: Create Child initiato groups
          [dellemc.powermax.host](https://urldefense.com/v3/__http:/dellemc.powermax.host__;!!LSAcJDlP!xozWFO69CgJlB3a_knzFj6cfoOUR-SqMFvTTyjiWApdPtphfL5zOBnQPaz7ewPZP4XsIBHSNJk9LP5Kg0ytTu1FlRPI$):
            unispherehost: "{{unispherehost}}"
            universion: "{{universion}}"
            verifycert: "{{verifycert}}"
            user: "{{user}}"
            password: "{{password}}"
            serial_no: "{{serial_no}}"
            host_name: "{{'IG_'+item.name | upper }}"           
            host_flags:
              consistent_lun: true
            state: 'present'
            initiators: "{{ item.initiators}}"
            initiator_state: 'present-in-host'
          register: childIgCreateResponse
          loop: "{{ hosts }}"
...
    hosts:
    - name: "REGTESTESX041"
      initiators:
        - "3311111111111EA2"
        - "3311111111111EA3"
    - name: "REGTESTESX042"
      initiators:
        - "3311111111111EA4"
        - "3311111111111EA5"

n. Step n See error

failed: [localhost] (item={'name': 'REGTESTESX041', 'initiators': ['3311111111111EA2', '3311111111111EA3']}) => {"ansible_loop_var": "item", "changed": false, "item": {"initiators": ["3311111111111EA2", "3311111111111EA3"], "name": "REGTESTESX041"}, "msg": "Adding initiators ['3311111111111EA2', '3311111111111EA3'] to host IG_REGTESTESX041 failed with error Bad or unexpected response from the storage volume backend API: Error PUT symmetrix resource. The status code received is 500 and the message is {'message': 'A problem occurred modifying the host resource: Error for: 000297900442/IG_REGTESTESX041: The operation can not be performed because the group is already in this state'}."}
failed: [localhost] (item={'name': 'REGTESTESX042', 'initiators': ['3311111111111EA4', '3311111111111EA5']}) => {"ansible_loop_var": "item", "changed": false, "item": {"initiators": ["3311111111111EA4", "3311111111111EA5"], "name": "REGTESTESX042"}, "msg": "Adding initiators ['3311111111111EA5', '3311111111111EA4'] to host IG_REGTESTESX042 failed with error Bad or unexpected response from the storage volume backend API: Error PUT symmetrix resource. The status code received is 500 and the message is {'message': 'A problem occurred modifying the host resource: Error for: 000297900442/IG_REGTESTESX042: The operation can not be performed because the group is already in this state'}."}

**Expected behavior**
Module should not care about case, WWN should be normalised on API side to match for idempotency regardless of upper|lower this is the behaviour in PowerMax CLI

**Screenshots**

**Logs**
If applicable, submit logs or stack traces from the affected services

**System Information (please complete the following information):**
 - OS/Version: RHEL 8.2
 - PowerMax Collection 1.8

**Additional context**

**Comment by anupamaloke** [comment]
@rawstorage, thank you for submitting this. We will add this to the backlog, triage and add a release milestone when available.

**Comment by rawstorage** [comment]
Thanks Anupam, note there are also some case sensitivity issues around Host and HostGroup names, this should also be addressed in the fix

**Comment by Jennifer-John** [comment]
Closing this issue as it is fixed as part of PR #28
