### ISSUE TITLE
[BUG]: Info Module is looping on all masking views to filter for lun addresses

### ISSUE THREAD

**Issue by rawstorage** [dell/ansible-powermax#30]
**Describe the bug**
Info Module is looping on all masking views to filter for lun addresses

**To Reproduce**
    - name: Get list of masking view connections with filter
      dellemc.powermax.info:
        unispherehost: "{{localDetail.mgmt_server}}"
        universion: "{{universion}}"
        verifycert: "{{verifycert}}"
        user: "{{credential.username}}"
        password: "{{credential.password}}"
        serial_no: "{{localDetail.array}}"
        gather_subset:
        - mv_connections
        filters:
        - filter_key: "volume_id"
          filter_operator: "equal"
          filter_value: "{{item.volumeId}}"
      loop: "{{ volDetail }}"
      register: mvConnResponse

...
n. Step n See error
Code is 
    def get_mv_connections_list(self, filters_dict=None):
        """Get the list of masking view connections of a given PowerMax or VMAX storage
        system"""

        try:
            LOG.info('Getting Masking View Connections List')
            array_serial_no = self.module.params['serial_no']
            masking_view_list = self.get_masking_view_list()
            mv_connections_list = []
            for masking_view_id in masking_view_list:
                connections = self.provisioning.get_masking_view_connections(masking_view_id, filters=filters_dict)
                if connections:
                    mv_connections_list.append(
                        {
                            'masking_view_id': masking_view_id,
                            'masking_view_connections': connections
                        }
                    )
            LOG.info('Got %d Getting Masking Views Connections from array %s',
                     len(mv_connections_list), array_serial_no)
            return mv_connections_list

**Expected behavior**
Customer should be able to filter on masking view, to correct a new optional paramter for masking view name should be allowed which would avoid the loop

**System Information (please complete the following information):**
 - Ansible Collection - Latest

**Additional context**
Masking view connections REST API is intensive on API server so running this the way it is is potentially going to slow down unisphere server for customer with large number of masking views.

**Comment by anupamaloke** [comment]
Closed by #35
