### ISSUE TITLE
[BUG]:fatal: [localhost]: FAILED! => {"changed": false, "msg": "Delete storage group X999RSWP_12312423_tmp99CRTEST_RSWP failed with error get_storage_group_snapshot_generation_list() got an unexpected keyword argument 'storagegroup_id' "}

### ISSUE THREAD

**Issue by rawstorage** [dell/ansible-powermax#31]
**Describe the bug**

storagegroup.py calls get_storage_group_snapshot_generation_list with the wrong parameter.

https://github.com/dell/ansible-powermax/blob/189e5ad993e5351d5c9dcdfcbb7ca40c6a993feb/plugins/modules/storagegroup.py#L1437C25-L1437C40

            for snap in snap_list:
                gen_list = self.replication.\
                    get_storage_group_snapshot_generation_list(
                        storagegroup_id=sg_name,
                        snap_name=snap)

Should be
            for snap in snap_list:
                gen_list = self.replication.\
                    get_storage_group_snapshot_generation_list(
                        storage_group_id=sg_name,
                        snap_name=snap)

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Delete storage group X999RSWP_12312423_tmp99CRTEST_RSWP failed with error get_storage_group_snapshot_generation_list() got an unexpected keyword argument 'storagegroup_id' "}

Please fix, issue seen at HSBC

**Comment by anupamaloke** [comment]
Closed by #35
